name: Continous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LISP: [abcl-bin, ccl-bin, cmu-bin, ecl, sbcl-bin]
    steps:
    - uses: actions/checkout@v1
    - name: install Lisp
      env:
        LISP: ${{matrix.LISP}}
      run: |
        sudo apt-get install -y build-essential automake libcurl4-openssl-dev
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
    - name: run test
      env:
        LISP: ${{matrix.LISP}}
      run: |
        export PATH=~/.roswell/bin:$PATH
        ros run -e '(pushnew :literate-test *features*)' \
            -e '(ql:quickload :literate-lisp)' \
            -e '(literate-lisp:with-literate-syntax (load "./literate-lisp.org"))' \
            -e '(ql:quickload :literate-demo)' \
            -e '(format t "Run test in ~A ~A~%" (lisp-implementation-type) (lisp-implementation-version))' \
            -e '(if (not (literate-lisp::run-test)) (uiop:quit 1))' \
            -e '(if (not (islands-puzzle::run-test)) (uiop:quit 1))' \
            -e '(uiop:quit 0)'
