name: Continous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LISP: [sbcl-bin]
    steps:
    - uses: actions/checkout@v1
    - name: Test
      uses: ./.github/actions/test
      with:
        lisp: ${{matrix.LISP}}
