name: Continous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LISP: [ccl-bin, sbcl-bin]
    steps:
    - uses: actions/checkout@v1
    - name: Test
      uses: ./.github/actions/test
      with:
        lisp: ${{matrix.LISP}}

      run: |
        export PATH=~/.roswell/bin:$PATH
        ros run -e '(pushnew :test *features*)' \
            -e '(ql:quickload :literate-lisp)' \
            -e '(literate-lisp:with-literate-syntax (load "./literate-lisp.org"))' \
            -e '(ql:quickload :literate-demo)' \
            -e '(format t "Run test in ~A ~A~%" (lisp-implementation-type) (lisp-implementation-version))' \
            -e '(if (not (literate-lisp::run-test)) (uiop:quit 1))' \
            -e '(if (not (islands-puzzle::run-test)) (uiop:quit 1))' \
            -e '(if (not (literate-demo::run-test)) (uiop:quit 1))' \
            -e '(uiop:quit 0)'
