name: Continous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LISP: [sbcl,abcl,ecl,ccl]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run:  docker pull ghcr.io/jingtaozf/literate-lisp/cl-base:v20211219
      - name: Test
        uses: ./.github/actions/test
        with:
          lisp: ${{matrix.LISP}}
